#' Earthquake observations from NOAA significant earthquake database
#'
#' @source National Oceanic and Atmospheric Administration Signficant earthquake database.
#'  \url{https://www.ngdc.noaa.gov/nndc/struts/form?t=101650&s=1&d=1}
#' @format A data frame with columns:
#' \describe{
#'  #'  \item{I_D}{I_D}
#'  \item{FLAG_TSUNAMI}{FLAG_TSUNAMI}
#'  \item{YEAR}{YEAR}
#'  \item{MONTH}{MONTH}
#'  \item{DAY}{DAY}
#'  \item{HOUR}{HOUR}
#'  \item{MINUTE}{MINUTE}
#'  \item{SECOND}{SECOND}
#'  \item{FOCAL_DEPTH}{FOCAL_DEPTH}
#'  \item{EQ_PRIMARY}{EQ_PRIMARY}
#'  \item{EQ_MAG_MW}{EQ_MAG_MW}
#'  \item{EQ_MAG_MS}{EQ_MAG_MS}
#'  \item{EQ_MAG_MB}{EQ_MAG_MB}
#'  \item{EQ_MAG_ML}{EQ_MAG_ML}
#'  \item{EQ_MAG_MFA}{EQ_MAG_MFA}
#'  \item{EQ_MAG_UNK}{EQ_MAG_UNK}
#'  \item{INTENSITY}{INTENSITY}
#'  \item{COUNTRY}{COUNTRY}
#'  \item{STATE}{STATE}
#'  \item{LOCATION_NAME}{LOCATION_NAME}
#'  \item{LATITUDE}{LATITUDE}
#'  \item{LONGITUDE}{LONGITUDE}
#'  \item{REGION_CODE}{REGION_CODE}
#'  \item{DEATHS}{DEATHS}
#'  \item{DEATHS_DESCRIPTION}{DEATHS_DESCRIPTION}
#'  \item{MISSING}{MISSING}
#'  \item{MISSING_DESCRIPTION}{MISSING_DESCRIPTION}
#'  \item{INJURIES}{INJURIES}
#'  \item{INJURIES_DESCRIPTION}{INJURIES_DESCRIPTION}
#'  \item{DAMAGE_MILLIONS_DOLLARS}{DAMAGE_MILLIONS_DOLLARS}
#'  \item{DAMAGE_DESCRIPTION}{DAMAGE_DESCRIPTION}
#'  \item{HOUSES_DESTROYED}{HOUSES_DESTROYED}
#'  \item{HOUSES_DESTROYED_DESCRIPTION}{HOUSES_DESTROYED_DESCRIPTION}
#'  \item{HOUSES_DAMAGED}{HOUSES_DAMAGED}
#'  \item{HOUSES_DAMAGED_DESCRIPTION}{HOUSES_DAMAGED_DESCRIPTION}
#'  \item{TOTAL_DEATHS}{TOTAL_DEATHS}
#'  \item{TOTAL_DEATHS_DESCRIPTION}{TOTAL_DEATHS_DESCRIPTION}
#'  \item{TOTAL_MISSING}{TOTAL_MISSING}
#'  \item{TOTAL_MISSING_DESCRIPTION}{TOTAL_MISSING_DESCRIPTION}
#'  \item{TOTAL_INJURIES}{TOTAL_INJURIES}
#'  \item{TOTAL_INJURIES_DESCRIPTION}{TOTAL_INJURIES_DESCRIPTION}
#'  \item{TOTAL_DAMAGE_MILLIONS_DOLLARS}{TOTAL_DAMAGE_MILLIONS_DOLLARS}
#'  \item{TOTAL_DAMAGE_DESCRIPTION}{TOTAL_DAMAGE_DESCRIPTION}
#'  \item{TOTAL_HOUSES_DESTROYED}{TOTAL_HOUSES_DESTROYED}
#'  \item{TOTAL_HOUSES_DESTROYED_DESCRIPTION}{TOTAL_HOUSES_DESTROYED_DESCRIPTION}
#'  \item{TOTAL_HOUSES_DAMAGED}{TOTAL_HOUSES_DAMAGED}
#'  \item{TOTAL_HOUSES_DAMAGED_DESCRIPTION}{TOTAL_HOUSES_DAMAGED_DESCRIPTION}
#' }
"quakes_df"
